```{r}
#Nhập dữ liệu từ bàn phím 
input <- read_line(prompt = "Nhập tên của bạn:")
print(paste("Tên của bạn là",input))
```

```{r}
# Nhập nhiều giá trị từ bàn phím
numbers <- scan()
print(numbers)
```

```{r}
#đọc dữ liệu từ 1 tệp
data <- read.table("F:/AI/Kì 5/DBR/vi du text file.txt",header = TRUE)
print(data)
```

```{r}
#đọc file csv
data <- read.csv("F:/AI/Kì 5/DBR/raw_seoul_bike_sharing.csv",header = TRUE)
print(data)
```

```{r}
install.packages("openxlsx")
```

```{r}
library(openxlsx)
```

```{r}
#đọc dữ liệu từ excel
data <- read.xlsx("F:/AI/Kì 5/DBR/Telco_customer_churn.xlsx")
print(data)
```

```{r}
#đọc dữ liệu từ url '
url <- "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/raw_seoul_bike_sharing.csv"
data <- read.csv(url, header = TRUE)
print(data)
```

```{r}
install.packages("jsonlite")
```

```{r}
library(jsonlite)
```

```{r}
#đọc dữ liệu từ json từ url 
url <- "https://query.data.world/s/sqwvfsfgw2q5ecupp36jdpgiscxgla?dws=00000"
data <- fromJSON(url)
print(data)
```

```{r}
install.packages("DBI")
install.packages("RSQLite")
```

```{r}
library(DBI)
library(RSQLite)
```

```{r}
#kết nối đến cơ sơ dữ liệu 
conn <- dbConnect(RSQLite::SQLite(), dbname = "F:/AI/Kì 5/DBR/chinook/chinook.db")
#thực hiện truy vẫn và lấy dữ liệu
query <- "SELECT * FROM customers"
data <- dbGetQuery(conn,query)

#đóng kết nối
dbDisconnect(conn)

print(data)
```

```{r}
install.packages("haven")
library(haven)
```

```{r}
#đọc dữ liệu từ tệp SPSS
data_spss <- read_sav("F:/AI/Kì 5/DBR/HLTH1025_2016.sav")
print(data_spss)
```

```{r}
#Đọc dữ liệu từ tệp STATA
data_stata <- read_dta("F:/AI/Kì 5/DBR/ZZHR62FL.DTA")
print(data_stata)
```

```{r}
data()
```

```{r}
#tải dataset mtcars
data("mtcars")
#hiển thị 6 dòng đầu
head(mtcars)
```

```{r}
#tóm tắt các biến 
summary(mtcars)
```

#### Demo

```{r}

#đọc dữ liệu từ url '
url <- "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0321EN-SkillsNetwork/labs/datasets/raw_seoul_bike_sharing.csv"
#đường dẫn lưu file trên máy tính 
file_path <- "F:/AI/Kì 5/DBR/raw_seoul_bike_sharing.csv"

#Tải về 
download.file(url,file_path)
```

```{r}
#đọc dữ liệu từ file csv
data <- read.csv(file_path)

#Hiển thị 6 dòng đầu 
head(data)
```

### a.Hiển thị các dòng đầu và cuối 

```{r}
#hiển thị 6 dòng đầu 
head(data)
#hiển thị 6 dòng cuối 
tail(data)
```
